export const siteConfig = {
    title: "Ukrainian cuisine",
    description: "Generated by Authentic Ukrainian cuisine crafted with traditional flavors, homemade recipes, and warm hospitality",
    navItems: [
    {href: "/", label: "recipes"},
    {href: "/ingridients", label: "ingridients"},
    {href: "/about", label: "us"}]
}