import { Content } from "next/font/google";

export const siteConfig = {
  title: "Ukrainian cuisine",
  description:
    "Generated by Authentic Ukrainian cuisine crafted with traditional flavors, homemade recipes, and warm hospitality",
  navItems: [
    { href: "/", label: "recipes" },
    { href: "/ingredients", label: "ingredients" },
    { href: "/about", label: "us" },
  ],
  pagesContent: {
    "/": {
      content: "",
    },
    "/ingredients": {
      content: "",
    },
    "/about": {
      content: `<h1>Ukrainian Cuisine: Comfort Food with a Proud History</h1>
    <p>
      Ukrainian cuisine is comfort food with a proud history — simple ingredients, bold flavors,
      and recipes passed down through generations.
    </p>
  </header>

  <p>
    Our website is a place where you can explore that taste in a modern, easy way. Here you’ll find
    traditional dishes like <strong>borshch</strong>, <strong>varenyky</strong>, <strong>holubtsi</strong>,
    <strong>deruny</strong>, <strong>banosh</strong>, <strong>pampushky</strong>, and <strong>узвар</strong> —
    with clear descriptions, beautiful photos, and step-by-step recipes you can actually follow.
  </p>

  <p>
    We also explain what makes each dish special:
    <em>where it comes from</em>, <em>when Ukrainians usually cook it</em>, and
    <em>which regions are most famous for it</em>.
  </p>

  <h2>What you can do on the site</h2>
  <ul>
    <li>
      Browse recipes by category:
      <span>soups, mains, pastries, drinks, desserts</span>
    </li>
    <li>Filter by <strong>difficulty</strong>, <strong>cooking time</strong>, and <strong>ingredients</strong></li>
    <li>Learn Ukrainian food vocabulary <em>(with pronunciation tips)</em></li>
    <li>Build a shopping list and save favorites</li>
    <li>
      Discover seasonal and regional selections:
      <span>Carpathian, Poltava-style, Odesa cuisine, and more</span>
    </li>
  </ul>

  <hr />

  <p>
    Whether you’re Ukrainian and missing home food, or you’re discovering Ukraine through cooking —
    this site helps you bring real Ukrainian flavors to your kitchen.
  </p>`,
    },
  },
};
