import { Content } from "next/font/google";

export const siteConfig = {
  title: "Ukrainian cuisine",
  description:
    "Generated by Authentic Ukrainian cuisine crafted with traditional flavors, homemade recipes, and warm hospitality",
  navItems: [
    { href: "/", label: "recipes" },
    { href: "/ingridients", label: "ingridients" },
    { href: "/about", label: "us" },
  ],
  pagesContent: {
    "/": {
      content: "",
    },
    "/ingredients": {
      content: "",
    },
    "/about": {
      content: `Ukrainian cuisine is comfort food with a proud history — simple
        ingredients, bold flavors, and recipes passed down through generations.
        Our website is a place where you can explore that taste in a modern,
        easy way. Here you’ll find traditional dishes like borshch, varenyky,
        holubtsi, deruny, banosh, pampushky, and узвар — with clear
        descriptions, beautiful photos, and step-by-step recipes you can
        actually follow. We also explain what makes each dish special: where it
        comes from, when Ukrainians usually cook it, and which regions are most
        famous for it. Use the site to: browse recipes by category (soups,
        mains, pastries, drinks, desserts) filter by difficulty, cooking time,
        and ingredients learn Ukrainian food vocabulary (with pronunciation
        tips) build a shopping list and save favorites discover seasonal and
        regional selections (Carpathian, Poltava-style, Odesa cuisine, and more)
        Whether you’re Ukrainian and missing home food, or you’re discovering
        Ukraine through cooking — this site helps you bring real Ukrainian
        flavors to your kitchen.`,
    },
  },
};
